### ISSUE TITLE
Index out of Range on 'dnmgr set'

### ISSUE THREAD

**Issue by rmoore** [andres-erbsen/dename#2]
When I attempt to set a pgp key with `dnmgr`, I get a runtime panic with an index out of range with the following traceback:

    [2] (ram@cipher ~)$ dnmgr set ram pgp D2365930F527EBE49D9C1883A3AB2AEC8095F57D
    panic: runtime error: index out of range
    
    goroutine 1 [running]:
    main.main()
            /home/ram/.go/src/github.com/andres-erbsen/dename/dnmgr/dnmgr/main.go:68 +0xd8a

I think this is because you're off by one in the value line, and I'll submit a PR shortly.

**Comment by andres-erbsen** [comment]
I think your assessment is correct. This was just recently introduced.
