### ISSUE TITLE
Page listing community servers

### ISSUE THREAD

**Issue by andres-erbsen** [andres-erbsen/dename#24]
There should be a nice page listing all public dename servers, regardless of whether they are included in the default config or not. I would be okay with just adding a .md file to the code repository here as a "works-for-now" solution. But first I would like to have some feedback on what information the file should contain. I am imagining the following fields for each server:

- hostname, port
- signing pubkey
- transport pubkey
- who runs the server (name, PGP key)
- country (of the server? server maintainer? both?)
- vps/colo/private hosting?
- Ideally-ideally it would also have uptime and version statistics, but this is way down my priority list right now.

**Comment by alokat** [comment]
Makes sense to me.

Is that really necessary?
- vps/colo/private hosting?
All that matters is, that there is a server.

Maybe it's better to know if there is something like
- isLeader / isCore or not.
If that is specified you know the server has high availability.

Statistics would be very cool, but I agree that this has very low priority right now.

**Comment by andres-erbsen** [comment]
Okay. How about

- who runs the server (name, PGP key)
- config entry (signing pk, transport pk, ip, port, ReadOnly)
- whatever else the maintainer would like to share there, limited to a couple of lines

**Comment by alokat** [comment]
Sounds good to me.
Maybe there will be more fields coming in the future. But I think this is a good start.

**Comment by andres-erbsen** [comment]
One important field as indicated by issue #23: what servers does this server know about.

**Comment by alokat** [comment]
What about the .md file? Any progress so far? Or do you wait until the client config diff is merged?

**Comment by andres-erbsen** [comment]
Here it is! https://github.com/andres-erbsen/dename/blob/master/community-servers.md
