### ISSUE TITLE
SK files with wrong file permissions

### ISSUE THREAD

**Issue by alokat** [andres-erbsen/dename#26]
Looks like the sk files of the server are created with the wrong file permission.
I'll check this out later.

**Comment by alokat** [comment]
The problem is that the sk file will be printed to stderr and the pk file to stdout.

$ go run utils/mkkey/mkkey.go 2> ~dename/keys/sk > ~dename/keys/pk
$ go run ../chatterbox/transport/transport-keygen/main.go 2> ~dename/keys/transport-sk > ~dename/keys/transport-pk

But the sk files need to have 600 as file permissions. I think the following command is better:

$ go run utils/mkkey/mkkey.go [path to create]
$ go run ../chatterbox/transport/transport-keygen/main.go [path to create]

This just creates the files with the needed permissions in the given directory.
If no path is specified the current one will be used.

Besides, that makes this command better scriptable too, because you can move and or copy files and don't need to consider about stderr or stdout.

Any comments?

**Comment by andres-erbsen** [comment]
I think that having the utilities write the keys to files with the correct permissions is a good idea. Just specifying a directory seems to leave ample room for user error to overwrite keys, maybe it would be better to specify a path to a nonexistent file, and append "-sk" and "-pk" to it to get the actual filenames. Even then, nothing should be overwritten.

**Comment by alokat** [comment]
Okay, I will implement something during the next days, kind of busy with university stuff right now. :)
Could you update the README with a "chmod 600" command for the two sk files, in order to avoid others
to run into the problems I did.

**Comment by andres-erbsen** [comment]
Updated: 54767a876d4bf32f20ca0fc066aacfcabadbaaf9

**Comment by alokat** [comment]
Thanks.

**Comment by alokat** [comment]
Dename version fixed:
https://github.com/alokat/dename/commit/78071a6c308630b9c741e889dcb9c8ed7920e468

Chatterbox will follow.
