### ISSUE TITLE
dnmgr freezes with invalid command-line arguments

### ISSUE THREAD

**Issue by morxa** [andres-erbsen/dename#33]
##### How to reproduce
Call `dnmgr` with insufficient arguments, e.g.
```
dnmgr set jabber "jabber@domain.com"
```
(note the missing name)
##### Expected behavior
`dnmgr` should print an error indicitating that the name `jabber` does not exist and possibly make a hint that the name is missing (since jabber is a field name).
##### Actual behavior
`dnmgr` does not print any errors and does not terminate.

**Comment by andres-erbsen** [comment]
Thanks for the report, I agree that this behavior is confusing and inconvenient. `dnmgr` is waiting for field contents to be entered using standard input; this is so to allow the following usage: `cat binary-public-key | dnmgr set name my-field` (passing the public key as an argument does not work if it contains `\0` bytes). However, `dnmgr` still could output an error if the name or profile field is invalid -- this would presumably avoid confusion most of the time.

**Comment by morxa** [comment]
I figured there was a reason for this, but I didn't think of stdin. The fix works perfectly, thanks!
