### ISSUE TITLE
cannot create a profile

### ISSUE THREAD

**Issue by sebastianrakel** [andres-erbsen/dename#35]
when i execute the command: 
```dnmgr init sebastian $invite_key```
i got following answer: 
```registration failed: not authorized```

i manually created the authorities.cfg with following content:
```
[verifier "mit-pilot"]
PublicKey = CiCheFqDmJ0Pg+j+lypkmmiHrFmRn50rlDi5X0l4+lJRFA==

[update "dename.mit.edu:6263"]
TransportPublicKey = 4f2i+j65JCE2xNKhxE3RPurAYALx9GRy0Pm9c6J7eDY=

[lookup "dename.alokat.org:6263"]
TransportPublicKey = IoEJsVcspYNiuymi+JMpfkL1usDy482qE8V4aGvKrkY=
```

my config file tree:
```
.config/dename
├── authorities.cfg
├── sebastian
│   └── sk
```

**Comment by andres-erbsen** [comment]
`dnmlookup sebastian ssh` returns a key with the description `sebastian@skurfuerst.local`. If this is not you, then somebody else simply registered the name before you got to it. The error message really should be more helpful, I will look into fixing that.

**Comment by sebastianrakel** [comment]
ok, no that is not me. i took another profile name and it worked.
