### ISSUE TITLE
dnmgr: add command to directly bump the expiration time

### ISSUE THREAD

**Issue by morxa** [andres-erbsen/dename#37]
It would be nice if `dnmgr` would allow something like `dnmgr set <name>` without any additional arguments. I would expect this to bump the expiration time without any other changes.

Possible use case:
I want to set up a cron job such that my profile won't be deleted due to expiration. As stated in the documentation, a simple `dnmgr set` causes a bump of the expiration time. However, in order to call `dnmgr set` successfully, I have to know a value of a field, or get it using `dnmlookup`. I would like to avoid that by calling `dnmgr set <name>` without any field value.

I guess this isn't a very important feature, but for me it would be a nice-to-have. If there is any way to do this already, please let me know.

**Comment by andres-erbsen** [comment]
Agreed, a command to bump the expiration time would be useful. Maybe `dnmgr update` instead, I imagine `dnmgr set` could be a common typo and displaying usage in response to it would help people out.

**Comment by morxa** [comment]
You're right, a `dnmgr update` would of course be much better, I've changed the title accordingly.

**Comment by alokat** [comment]
Hi, this commit should to the trick.  #39

**Comment by alokat** [comment]
Andres just merged the commit into master. @morxa could test if this is what you expected. If it is,
this issue can be closed, I guess.

**Comment by morxa** [comment]
Thanks!
