### ISSUE TITLE
Check for already registered names

### ISSUE THREAD

**Issue by alokat** [andres-erbsen/dename#42]
Hi,

is there any progress regarding the check for names that are already registered?
We had that problem a while ago.

I would like to offer a pull request, but @andres-erbsen is the only one who can create new invites, so how far is your diff? :)

**Comment by andres-erbsen** [comment]
Confirming that an extra invite does get used up when trying to register a taken name:
~~~~~~~~~~~~~~~~~~~~~~~
# fresh invites used to reproduce here: xvebJTMqn7ono8SgoKPzag== NZjhT8ITl09pSLc1Q0Px2g==, D6IxGOvT+locehVgVR26cQ== 
$ dnmgr init gQPjuIl3574iTW2BwyqnIA1 xvebJTMqn7ono8SgoKPzag==
$ mv ~/.config/dename/gQPjuIl3574iTW2BwyqnIA1{,.bak}
$ dnmgr init gQPjuIl3574iTW2BwyqnIA1 NZjhT8ITl09pSLc1Q0Px2g==
registration failed: not authorized
$ dnmgr init gQPjuIl3574iTW2BwyqnIA2 NZjhT8ITl09pSLc1Q0Px2g==                                                                                                  
registration failed: invite already used
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
After bb79881dfbd81ebd43c8197518d0e5974a94c501, a proposed fix:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$ mv ~/.config/dename/gQPjuIl3574iTW2BwyqnIA1{,.bak2}
$ dnmgr init gQPjuIl3574iTW2BwyqnIA1 D6IxGOvT+locehVgVR26cQ== 
registration failed: name already used
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I don't actually remember the issue we had with this earlier, so I am not closing this bug now. Please close it if the issue I fixed actually is the one you reported. And, if you ever need invites for testing or give-away purposes, just shoot me an email. I finally have some time to work on this again.

**Comment by alokat** [comment]
I thing that should do the trick. It's just to inform the user why the registration of a new name failed.
So, this diff is okay with me and I will close this issue.
