### ISSUE TITLE
RFC: Replace TLS

### ISSUE THREAD

**Issue by andres-erbsen** [andres-erbsen/dename#7]
TLS is a great thing on the web, but given that `dename` inherently needs to have servers' public keys in the configuration, we don't really need TLS here. Currently, TLS configuration is also the most annoying part of setting up and using non-default servers -- which I encourage and want to make as easy as possible. Therefore, I am proposing to replace TLS with a simple Diffie-Hellman key exchange followed by counter-nonced nacl/box messages.

Specifically, each server that handles lookups or registrations would have a Curve25519 public key which it would use to vouch for a second, ephemeral Curve25519 public key, which would be used to generate a shared secret with the client. The ephemeral key-exchange would happen *first*, then encryption would be turned on and the vouching would happen over the encrypted and authenticated channel to prevent misbinding attacks.

The server's long term public key for the connection security would be stored in the client configuration the same way the signing public key is.

This differs from Hugo Krawczyk's [SIGMA-R (page 20)](http://webee.technion.ac.il/~hugo/sigma-pdf.pdf) by (1) MAC-ing strictly more data and (2) using authenticated encryption to vouch for the ephemeral key instead of a signature. The "session ID", "info" and "nonce" from "full-fledge" description in the appendix are set equal to the ephemeral public key. These elements are not at all present in the [journal version](http://www.iacr.org/cryptodb/archive/2003/CRYPTO/1495/1495.pdf) of the paper and the relevant [proofs](http://eprint.iacr.org/2002/120) only require a "session id" that is not reused -- which is true for randomly generated DH public keys (with overwhelming probability). It remains unclear to me why the appendix of the full paper separates the nonce from the DH public value -- the simpler version seems simply as good our purposes.

Why not use something "well-established"? Mainly because I am not aware of anything that (a) has a simple argument for its cryptographic soundness and (b) is simple to implement or integrate with a "mere" userland application.
- TLS is mainly meant for use with the x509 PKI, which is just bloat for us. The track record of [other ways](https://tools.ietf.org/html/rfc5929) of using TLS do not [inspire confidence](https://secure-resumption.com/#channelbindings).
- [CurveCP](http://curvecp.org/packets.html) looks nice, but it runs over UDP and requires a congestion control system
- [CurveZMQ](http://curvezmq.org/page:read-the-docs#toc16) is an almostr direct port of CurveCP to TCP.
- [ntor](https://gitweb.torproject.org/torspec.git/tree/proposals/216-ntor-handshake.txt) follows the same general pattern and is only "established" in the context of TOR.
- [pond/transport](https://github.com/agl/pond/blob/master/transport/transport.go) has a Go implementation and it is very similar to SIGMA as well, but again, it is used just there.
- <http://nacl.cr.yp.to/box.html> section "Security model" describes how to use nacl/box and counter-based message nonces the same way as this proposal does after the vouching.

I implemented this for another project of mine: <https://github.com/andres-erbsen/chatterbox/blob/master/transport/transport.go>; the implementation consists of about 150 lines of Go code, is symmetric with respect to which party is the server, and follows the simple description of SIGMA-R directly. It is in my opinion much easier to understand and audit than any of the above.

Comments and proposals are welcome.

**Comment by alokat** [comment]
Makes sense to me. Because a) it avoids the whole "create a Certificate, signed by a RootCA" thing.
So this part of the config can be removed and a) as you already mentioned: the server already has a public key. So TLS solves more problems than dename has.

**Comment by ariddell** [comment]
This makes sense. I wonder if there's a solution where the client doesn't need to store both public keys (signing and long-term). There's certainly a lot of thinking about nacl-based transport security over at telehash (under the name 'e3x'): https://github.com/telehash/telehash.org/tree/master/v3/e3x There's also a go implementation.

**Comment by ariddell** [comment]
Forgive me if I'm missing something (I'll take a look at SIGMA-R shortly). Can the public signing key be the long-term connection key as well?

**Comment by andres-erbsen** [comment]
Indeed, we could use the signing key to vouch for ephemeral DIffie-Hellman keys used for connection encryption. I don't think there is any need to merge them, however -- copying three lines to the client config does not seem harder than copying two. As for reasons for keeping them separate, I can think of two. First, legally compelling somebody to reveal an encryption-related key seems strictly easier than requiring them to hand over a key that is only involved in providing authentication. Second, it would be possible to run "just" the frontend on a machine that is not trusted to do dename signing (this could be done in other ways, but not even having that machine's signing key in the config is very obviously excluding them).

**Comment by ariddell** [comment]
This makes perfect sense. And providing a long-term communication key is
far easier than providing a signed TLS cert.

My lingering concern is around the lack of a common standard and
nomenclature for this kind of thing. It would be great to use something
existing or standardization-bound. Since Pond already has a considerable
audience, what are the downsides to using that implementation/spec?

**Comment by andres-erbsen** [comment]
There is no indication that Pond's transport encryption was designed with plug-and-play reusability in mind, and the current implementation is tied to Pond closely enough that we would need to change code to use it. We could probably make it work here, but I am thinking of building a dename-authenticated encrypted netcat-like tool next and it would not be that easy to use it there due to various client-server asymmetries in the spec.

I am going to continue to try out chatterbox/transport for `dename.mit.edu` now, with a backwards-compatible TLS frontend.

**Comment by andres-erbsen** [comment]
The change discussed here has landed. Any further improvements/modifications can be discussed in new issues.
